// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecordTime.Data;

#nullable disable

namespace RecordTime.Data.Migrations
{
    [DbContext(typeof(RecordTimeDbContext))]
    [Migration("20251116141312_OptimizeDatabaseIndexes")]
    partial class OptimizeDatabaseIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("RecordTime.Core.Models.AppSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowTitleHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityType")
                        .HasDatabaseName("IX_Sessions_ActivityType");

                    b.HasIndex("EndTime")
                        .HasDatabaseName("IX_Sessions_EndTime");

                    b.HasIndex("LastHeartbeat")
                        .HasDatabaseName("IX_Sessions_LastHeartbeat");

                    b.HasIndex("ProcessName")
                        .HasDatabaseName("IX_Sessions_ProcessName");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("IX_Sessions_StartTime");

                    b.HasIndex("StartTime", "EndTime")
                        .HasDatabaseName("IX_Sessions_StartTime_EndTime");

                    b.ToTable("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
