// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecordTime.Data;

#nullable disable

namespace RecordTime.Data.Migrations
{
    [DbContext(typeof(RecordTimeDbContext))]
    [Migration("20251125091140_AddTimeBudgetTables")]
    partial class AddTimeBudgetTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("RecordTime.Core.Models.AppSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowTitleHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityType")
                        .HasDatabaseName("IX_Sessions_ActivityType");

                    b.HasIndex("EndTime")
                        .HasDatabaseName("IX_Sessions_EndTime");

                    b.HasIndex("LastHeartbeat")
                        .HasDatabaseName("IX_Sessions_LastHeartbeat");

                    b.HasIndex("ProcessName")
                        .HasDatabaseName("IX_Sessions_ProcessName");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("IX_Sessions_StartTime");

                    b.HasIndex("StartTime", "EndTime")
                        .HasDatabaseName("IX_Sessions_StartTime_EndTime");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("RecordTime.Core.Models.DailyBudgetProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GoalReached")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeBudgetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_DailyBudgetProgress_Date");

                    b.HasIndex("TimeBudgetId")
                        .HasDatabaseName("IX_DailyBudgetProgress_TimeBudgetId");

                    b.HasIndex("TimeBudgetId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_DailyBudgetProgress_TimeBudgetId_Date");

                    b.ToTable("DailyBudgetProgresses");
                });

            modelBuilder.Entity("RecordTime.Core.Models.GoalSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BasedOnDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HistoricalAverageMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessResult")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SuggestedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuggestedType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_GoalSuggestions_Category");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_GoalSuggestions_ExpiresAt");

                    b.HasIndex("IsProcessed")
                        .HasDatabaseName("IX_GoalSuggestions_IsProcessed");

                    b.HasIndex("ProcessName")
                        .HasDatabaseName("IX_GoalSuggestions_ProcessName");

                    b.ToTable("GoalSuggestions");
                });

            modelBuilder.Entity("RecordTime.Core.Models.TimeBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReminderEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReminderThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_TimeBudgets_Category");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("IX_TimeBudgets_IsEnabled");

                    b.HasIndex("ProcessName")
                        .HasDatabaseName("IX_TimeBudgets_ProcessName");

                    b.ToTable("TimeBudgets");
                });

            modelBuilder.Entity("RecordTime.Core.Models.DailyBudgetProgress", b =>
                {
                    b.HasOne("RecordTime.Core.Models.TimeBudget", "TimeBudget")
                        .WithMany()
                        .HasForeignKey("TimeBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeBudget");
                });
#pragma warning restore 612, 618
        }
    }
}
